name: naan_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  get: 4.6.5
  lottie: ^1.3.0
  get_cli: ^1.8.1
  # flutter_lints: ^2.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/home_page/
    - assets/svg/
    - assets/onboarding_page/
    - assets/onboarding_page/lottie/
  uses-material-design: true



  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 700
    - family: Space Grotesk
      fonts:
        - asset: fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
        - asset: fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
